import "./globals.scss"
import { Metadata } from 'next'
import { Header } from '@/components/Header/Header'
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import { BurgerMenu } from "@/components/BurgerMenu/BurgerMenu";
import { Montserrat } from "next/font/google";
config.autoAddCss = false;

export const metadata: Metadata = {
  title: 'Школа IT | King Code',
  description: 'Generated by create next app',
}

const montserrat = Montserrat({ subsets: ['latin', 'cyrillic'], weight: ["400"] })

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ru">
      <body className={montserrat.className}>
        <Header />
        {children}
        <BurgerMenu />
      </body>
    </html>
  )
}
