import "./globals.scss"
import { Metadata } from 'next'
import { Header } from '@/components/Header/Header'
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import { BurgerMenu } from "@/components/BurgerMenu/BurgerMenu";
import { Montserrat } from "next/font/google";
import { Footer } from "@/components/Footer/Footer";
import { Curtain } from "@/components/UI/Curtain/Curtain";
import { Modal } from "@/components/Modal/Modal";
import { SocialBeforeFooter } from "@/components/SocialBeforeFooter/SocialBeforeFooter";
config.autoAddCss = false;

export const metadata: Metadata = {
  title: 'Школа IT | King Code',
  description: 'Generated by create next app',
  viewport: "width=device-width, initial-scale=1"
}

const montserrat = Montserrat({ subsets: ['latin', 'cyrillic'], weight: ["500", "600", "700"]});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ru">
      <body className={montserrat.className}>
        <div className="helper">
          <div className="content">
            <Header />
            <main>
              {children}
            </main>
            <SocialBeforeFooter />
            <BurgerMenu />
            <Curtain />
            <Modal />
          </div>
          <Footer />
        </div>
      </body>
    </html>
  )
}
